server:
  port: 9001
#连接池
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudtest
    username: root
    password: 1234
  application:
    name: user-service
mybatis:
  type-aliases-package: com.bob.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
